FROM alpine:3.12.3

RUN apk add --no-cache --purge -uU \
	    ca-certificates curl cgit lighttpd git \
    && echo 'include "cgit.conf"' >> /etc/lighttpd/lighttpd.conf

EXPOSE 80

COPY cgit.conf /etc/lighttpd/cgit.conf

VOLUME /etc/cgitrc, /var/repositories

CMD lighttpd -D -f /etc/lighttpd/lighttpd.conf